version: "3.9"
services:
  php-apache-environment:
    container_name: php-apache
    image: my_apache
    # command: bash -c "composer install"
    volumes:
      - ./app:/var/www/html/
    ports:
      - 4000:80
